### ISSUE TITLE
Publish this as a Gem

### ISSUE THREAD

**Issue by aaronprice** [teamsnap/omniauth-teamsnap#4]
Hey guys,

We're currently using this code and pointing to your master branch in our gem file because it's not yet been published to https://rubygems.org/. Could you publish this code to avoid the effect of breaking changes.

Thank you.

**Comment by semmons99** [comment]
1.0.0 was just released to rubygems.org

**Comment by aaronprice** [comment]
Thanks Shane, you are the man!
